"""add memory embedding

Revision ID: 3c32b496086e
Revises: 47c7e35b3b82
Create Date: 2026-05-08 22:38:27.581295

"""

from typing import Sequence, Union
from pgvector.sqlalchemy import Vector
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3c32b496086e"
down_revision: Union[str, Sequence[str], None] = "47c7e35b3b82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column("memories", sa.Column("embedding", Vector(dim=768), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("memories", "embedding")
    # ### end Alembic commands ###
