"""change memory_type to enum

Revision ID: 47c7e35b3b82
Revises: e72614301c84
Create Date: 2026-05-08 19:46:23.286416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47c7e35b3b82'
down_revision: Union[str, Sequence[str], None] = 'e72614301c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memories', 'memory_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('profile', 'preference', 'decision', 'project_context', name='memory_type_enum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memories', 'memory_type',
               existing_type=sa.Enum('profile', 'preference', 'decision', 'project_context', name='memory_type_enum', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
